### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by familqasimov** [yafp/GimmePassword#9]
Hi sir. I'm graphic designer.I have studied your work and I think a new design will make you more visible.  I would like to offer you another logo. I can give you all the formats of the design free. If you want a change please specify.

![logotype](https://user-images.githubusercontent.com/36432269/39067197-e7cbaf12-44e8-11e8-9985-c8e6c95f3a65.png)

**Comment by yafp** [comment]
@familqasimov 
First of all, thanks for the logo-designs.
Please give me some time to think about the suggested logo change.
I'll come back to this issue in some days.

Best regards
yafp

**Comment by familqasimov** [comment]
First of all, I'm glad that you liked this design. I would like you write me what you like from the logo, please. I wrote one number for each logo. If possible, you wrote me the color and size of the logo you selected. Thank you.

**Comment by familqasimov** [comment]
Hello sir. I changed the logo you selected and made the new version. I think this is also a pleasant one.

![1](https://user-images.githubusercontent.com/36432269/39226641-b9cc3670-4864-11e8-9388-f7e710d5a79d.png)


version 2

![2](https://user-images.githubusercontent.com/36432269/39226647-c981ff5a-4864-11e8-8082-c812846bbdee.png)


all file hire https://drive.google.com/drive/folders/1B0B00WxMh9VJiJdyuhGR_hxIkc6Fi5q-

Best regards
Famil Qasomov.

**Comment by yafp** [comment]
Thanks @familqasimov 
the images in the current 'version 1' folder look great. Thanks for updating the color.

Please note:
i liked the 'reload' symbol inside the lock on the previous version even better then the G in the current.
In case you would like to change this particular part back it would be awesome.
if not i would use the current 'version 1'.

Last questions (so far:))
Do you agree regarding the fact that i can freely use the icon? 
And should i add you to the contributor list?

**Comment by familqasimov** [comment]
Hello sir. I was very glad with your like this work and your attention to me was pleasing. I reviewed it again folder-1 sizes and added it to the name reload-folder for the previous version. Use it with great pleasure if you like it.

I would like you add me to the  the contributor list and and you would showed the logo you selected in your current project.

For your upcoming new projects please contact me at github or at familqasimov@gmail.com. I wish you good luck.

re-examine here again please.  https://drive.google.com/drive/folders/10c1KSBvZR301glSHkHLhN5l9DncP418J

Best regards
Famil Qasomov.

**Comment by yafp** [comment]
Big thanks, ill add the new icons with the next upcoming version.

**Comment by yafp** [comment]
@familqasimov 
The new version (1.2.0) is online and comes with your new logo.
I've added you to the contributors list.
Some screenshots in the store still show the old UI as i have to redo them ...but apart from that the migration is done.

Thanks once again for the support.

**Comment by familqasimov** [comment]
I also thanks my friend for used my contribution.

Best regards
Famil Qasimov.

7 may 2018, B.e 09:48 tarixində fidel <notifications@github.com> yazdı:
